### PR TITLE
Point estimate interface

### LINKED ISSUE #50: Rethink point estimate interface
We need to decide on the optimal interface for extracting **point estimates** of the three Dawid-Skene parameters. 

There are two things to consider here: 

What names should be use of the parameters? Principally should we favor mathematical names i.e *pi*, *theta*, *z* or names based on the interpretation of the parameters i.e. *prevalence probabilities*, *error matrices*, *latent class*?

What should the function we use to extract the point estimates be called? Some options:

* `extract_{parameter name}`: This is currently implemented. 
      
    - Pros: {rstan} used `extract(fit, pars = {parameter names}) and consistency with this interface was the original reason for this choice. It should be noted that the {rstan} extract function extracts **posterior draws** not point estimates. 

     - Cons: Not 'symmetric' with `plot(fit, par = {parameter name}`. Doesn't describe what we are extracting i.e. no mention of posterior, point estimate etc. Inconsistent with {rstan} behavior re draws vs point estimates. 

* `coef()`: This is what is used in {brms} and {rstanarm}, the two major high level Stan interfaces. 

    - Pros: Consistency with {brms} and {rstanarm}

    - Cons: Both {brms} and {rstanarm} fit Bayesian GLM extensions, multilevel models etc, so the models always contain coefficients in the traditional regression sense. None of the models implemented in {rater} can be easily interpreted as coefficients. 

* A new function: `point_estimates()` or similar.

    - Pros: Descriptive name, no potential for confusion with other interfaces. 

    - Cons: How should the function handle fits using optimization vs MCMC? Both methods give point estimates, but different types of point_estimates. Maybe an argument `type`: could be "default" by default which would return MAP or mean depending on what was sensible, but could be specified.  The function is also more verbose but that may not matter if/when we switch to the {rstantools} generics more generally.

cc @dvukcevic Thoughts?

### PR DESCRIPTION
**Pull request by jeffreypullin**
This branch contain the new `point_estimate` interface. 

Fixes #50

### CODE REVIEW

**Comment by jeffreypullin** [comment]
Currently this branch implements: 
```r
> point_estimate(x, pars = "pi")
[[1]]
[1] 0.37337030 0.40577554 0.14863599 0.07221817
```
i.e. we don't drop the list in the length 1 case

**Comment by dvukcevic** [comment]
Looks good, especially the choice of retaining the list for the length 1 case.

Some other things:

- [ ] Need to export this method
- [ ] Name the components in the output list
- [ ] Name the elements/rows/columns in each type of output (pi, theta, z)

**Comment by jeffreypullin** [comment]
What do you have in mind @dvukcevic for "Name the elements/rows/columns in each type of output (pi, theta, z)"?

I have this for `pi`, but I'm not sure what would be best for `z/theta`

```
> point_estimate(fit, pars = "pi")
$pi
     pi[1]      pi[2]      pi[3]      pi[4] 
0.37191079 0.40862402 0.14764762 0.07181757 
```

**Comment by dvukcevic** [comment]
Hmm...good question.  I initially just thought it would be helpful to name things so they are easier to navigate and not get confused, but I'm not sure if there are natural names to assign here.  Perhaps we can spin this out as a separate issue to think about in the future sometime?

**Comment by jeffreypullin** [comment]
I've made a new issue #70

**Comment by jeffreypullin** [comment]
Okay, I think this is now ready - I will merge if/when CI passes

**Comment by dvukcevic** [comment]
Great work, @jeffreypullin!

I see that the various `extract_` generic functions are still defined in `rater_fit_class.R`, but you have removed the methods that it used to call (see aba520e0).  I guess we don't need them any longer and should remove them?

**Comment by jeffreypullin** [comment]
Good spot, I've opened an issue to track the removal of the unused generics #73

**Pull request merged**
